# Site settings
baseurl = "http://example.org" #without ending slash
languageCode = "en-us"
theme = "hugo-tile-theme"
title = "Hugo Tile Theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXX-Y"

[params]
	
	# Images settings
	# Icons, backgrounds and avatars folders are placed in theme's static/img folder.
	# You may place your images in corresponding folders and then set only filenames below to
	# change page's appearance
	
	favicon = "favicon.ico"
	appletouchicon = "apple-touch-icon-precomposed.png"
	background = "background.jpg"

	# Custom styling
	# To customize the styling of this theme, uncomment and edit the following line to point 
	# to your site's css in the assets/ directory. 

	# custom_css = ["css/foo.bar"]
	
	# Personal settings
	
    name = "Runnably"
	
		
	# Social settings
	# You may change these with your social links or add others

	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "#"

	[[params.social]]
		title = "Instagram"
		icon = "fa-instagram"
		link = "#"
		
	[[params.social]]
		title = "Facebook"
		icon = "fa-facebook"
		link = "#"
	
	# Footer settings
	[params.footer]
		copyright = "Runnably"
		
